### ISSUE TITLE
http://gnome.asia redirects to 2016.gnome.asia

### ISSUE THREAD

**Issue by PrabhanshuAttri** [GNOME-Asia/2018.gnome.asia#1]
If you visit [http://gnome.asia](http://gnome.asia), you will be redirected to [http://2016.gnome.asia](http://2016.gnome.asia). As GNOME Asia 2018 is up, I think it should redirect to 2018.gnome.asia.

**Comment by Nienzu** [comment]
It's right!! We will update the DNS setting as soon as possible.
Thanks!

**Comment by PrabhanshuAttri** [comment]
It's fixed now. Closing this.
